name: in_library
description: A flutter project to In Fiscal.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  card_swiper: ^3.0.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_riverpod: ^2.4.3
  go_router: ^11.1.2
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  mysql1: ^0.20.0
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

  assets:
    - assets/images/
